[package]
name = "beacon-rs"
version = "0.1.0"
edition = "2024"
resolver = "2"
rust-version = "1.97"

[[bin]]
name = "beacon-rs"
harness = false

[profile.release]
opt-level = "s"

[profile.dev]
debug = true
opt-level = "z"

[patch.crates-io]
esp-idf-sys = { git = "https://github.com/esp-rs/esp-idf-sys.git" }
esp-idf-hal = { git = "https://github.com/esp-rs/esp-idf-hal.git" }
esp-idf-svc = { git = "https://github.com/esp-rs/esp-idf-svc.git" }

[dependencies]
log = "0.4"
esp-idf-sys = "0.37"
esp-idf-svc = { version = "0.52.1", features = ["critical-section"] }
esp-idf-hal = "0.46.2"
sstv = { path = "../sstv" }

[build-dependencies]
embuild = "0.33"
image = "0.25.1"
