cargo-features = ["panic-immediate-abort"]

[package]
name = "beacon"
version = "0.1.0"
edition = "2024"
resolver = "2"
rust-version = "1.97"

[[bin]]
name = "beacon"
harness = false

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "immediate-abort"

[profile.dev]
debug = true
strip = "debuginfo"
opt-level = "z"

[patch.crates-io]
esp-idf-sys = { git = "https://github.com/esp-rs/esp-idf-sys.git" }
esp-idf-hal = { git = "https://github.com/esp-rs/esp-idf-hal.git" }
esp-idf-svc = { git = "https://github.com/esp-rs/esp-idf-svc.git" }

[dependencies]
log = "0.4"
esp-idf-sys = "0.37"
esp-idf-svc = { version = "0.52.1", features = ["critical-section"] }
sstv = { git = "https://github.com/unexcellent/sstv.git", branch = "main" }

[build-dependencies]
embuild = "0.33"

[package.metadata.esp-idf-sys]
extra_components = [
    { bindings_header = "src/camera/bindings.h" },
    { component_dirs = ["cmake_override/isp_patch"] }
]
