[build]
target = "riscv32imafc-esp-espidf"

[target.riscv32imafc-esp-espidf]
linker = "ldproxy"
runner = "local/flash.sh"
rustflags = [
    "--cfg", "espidf_time64",
]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32p4"
ESP_IDF_VERSION = "v5.5.3"
ESP_IDF_TOOLS_INSTALL_DIR = "workspace"
IDF_PATH = { value = ".embuild/espressif/esp-idf/v5.5.3", relative = true, force = true }
IDF_PYTHON_ENV_PATH = { value = ".embuild/espressif/python_env/idf5.5_py3.13_env", relative = true, force = true }
